version: '3.8'

services:
  web:
    build: .
    ports:
      - "80:8080"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-*}
    volumes:
      - .:/app
    restart: unless-stopped 